name: Build executables

on: [push]

env:
  VERSION: "5.2"

jobs:
  build-matrix:
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, windows-2019, macos-10.15, macos-11, macos-12]
        include:
          - os: windows-2019
            suffix: .exe
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Build
      run: |
        . ./build_scripts/install_dependencies.sh ${{ matrix.os }}
        . ./build_scripts/build.sh ${{ matrix.os }}
      shell: bash
    - name: Release
      uses: softprops/action-gh-release@v1
      # if: startsWith(github.ref, 'refs/tags/')
      with:
        draft: true
        files: | # ./photomosaic-maker-${{ env.VERSION }}-${{ matrix.version }}-x64-build.tar.gz
          ./dist/photomosaic-maker-${{ env.VERSION }}-${{ matrix.os }}-x64${{ matrix.suffix }}
          ./dist/photomosaic-maker-${{ env.VERSION }}-${{ matrix.os }}-x64.tar.gz